/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistanegocio;

import controlnegocio.Estructura;
import java.math.BigDecimal;

/**
 *
 * @author User
 */
public class VentanaInicial extends javax.swing.JFrame {
    
    Estructura estructura;

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        iniciarMisComponentes();
        
        this.estructura = new Estructura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPorcentajeConsumo = new javax.swing.JTextField();
        txtPorcentajeHipotecario = new javax.swing.JTextField();
        txtPorcentajeCorporativo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtPorcentajeInversiones = new javax.swing.JTextField();
        cmbPorcentajeOperaciones = new javax.swing.JComboBox<>();
        txtEnfoqueDeNegocio = new javax.swing.JTextField();
        lblErrorPorcentajeConsumo = new javax.swing.JLabel();
        lblErrorPorcentajeHipotecario = new javax.swing.JLabel();
        lblErrorPorcentajeCorporativo = new javax.swing.JLabel();
        lblErrorPorcentajeInversiones = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblApetitoRiesgo = new javax.swing.JLabel();
        lblErrorPorcentajeConsumo1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCrecimientoEconomico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDesempleo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCapitalBase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbApalancamiento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFinanciamiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFondoDeNegocio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblCalificacionBancaria = new javax.swing.JLabel();
        lblErrorCapitalBase = new javax.swing.JLabel();
        lblErrorCapitalBase1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGuardar = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuReporte = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuFondeo = new javax.swing.JMenuItem();
        menuLineasNegocio = new javax.swing.JMenuItem();
        menuCarteras = new javax.swing.JMenuItem();
        menuTablaMora = new javax.swing.JMenuItem();
        menuLiquidez = new javax.swing.JMenuItem();
        menuSuficiencia = new javax.swing.JMenuItem();
        menuCoberturas = new javax.swing.JMenuItem();
        menuSolvencias = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador Bancario");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setText("Estructura");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel11.setText("Carteras:");

        jLabel12.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel12.setText("% Consumo:");

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel13.setText("% Hipotecario:");

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel14.setText("% Corporativo:");

        txtPorcentajeConsumo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        txtPorcentajeConsumo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentajeConsumoKeyReleased(evt);
            }
        });

        txtPorcentajeHipotecario.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        txtPorcentajeHipotecario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentajeHipotecarioKeyReleased(evt);
            }
        });

        txtPorcentajeCorporativo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        txtPorcentajeCorporativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentajeCorporativoKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel15.setText("% Inversiones:");

        jLabel16.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel16.setText("% Operaciones:");

        txtPorcentajeInversiones.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtPorcentajeInversiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentajeInversionesKeyReleased(evt);
            }
        });

        cmbPorcentajeOperaciones.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cmbPorcentajeOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "10", "5" }));
        cmbPorcentajeOperaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPorcentajeOperacionesItemStateChanged(evt);
            }
        });

        txtEnfoqueDeNegocio.setEditable(false);
        txtEnfoqueDeNegocio.setBackground(new java.awt.Color(255, 255, 102));
        txtEnfoqueDeNegocio.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        txtEnfoqueDeNegocio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblErrorPorcentajeConsumo.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorPorcentajeConsumo.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPorcentajeConsumo.setText("...");

        lblErrorPorcentajeHipotecario.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorPorcentajeHipotecario.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPorcentajeHipotecario.setText("...");

        lblErrorPorcentajeCorporativo.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorPorcentajeCorporativo.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPorcentajeCorporativo.setText("...");

        lblErrorPorcentajeInversiones.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorPorcentajeInversiones.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPorcentajeInversiones.setText("...");

        jLabel17.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel17.setText("Apetito de Riesgo:");

        lblApetitoRiesgo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblApetitoRiesgo.setForeground(new java.awt.Color(0, 102, 0));
        lblApetitoRiesgo.setText("...");

        lblErrorPorcentajeConsumo1.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorPorcentajeConsumo1.setForeground(new java.awt.Color(153, 204, 255));
        lblErrorPorcentajeConsumo1.setText("Debe ser numerico_____");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtEnfoqueDeNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPorcentajeHipotecario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentajeCorporativo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcentajeConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorPorcentajeHipotecario)
                            .addComponent(lblErrorPorcentajeCorporativo)
                            .addComponent(lblErrorPorcentajeConsumo)
                            .addComponent(lblErrorPorcentajeConsumo1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPorcentajeInversiones, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorPorcentajeInversiones))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPorcentajeOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblApetitoRiesgo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblApetitoRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErrorPorcentajeConsumo1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPorcentajeConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorPorcentajeConsumo))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPorcentajeHipotecario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPorcentajeHipotecario)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPorcentajeCorporativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPorcentajeCorporativo))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPorcentajeInversiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPorcentajeInversiones))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbPorcentajeOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(txtEnfoqueDeNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel10.setText("Enfoque de Negocio:");

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("<html>Crecimiento<br>Económico\n");

        txtCrecimientoEconomico.setEditable(false);
        txtCrecimientoEconomico.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("<html>Desempleo\n");

        txtDesempleo.setEditable(false);
        txtDesempleo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("Capital Base ₡:\n");

        txtCapitalBase.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        txtCapitalBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCapitalBaseKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel5.setText("Apalancamiento:");

        cmbApalancamiento.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        cmbApalancamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "7", "3" }));
        cmbApalancamiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbApalancamientoItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel6.setText("Financiamiento ₡: ");

        txtFinanciamiento.setEditable(false);
        txtFinanciamiento.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setText("Fondo de Negocio ₡: ");

        txtFondoDeNegocio.setEditable(false);
        txtFondoDeNegocio.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel8.setText("Calificación Bancaria:");

        lblCalificacionBancaria.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblCalificacionBancaria.setForeground(new java.awt.Color(0, 102, 0));
        lblCalificacionBancaria.setText("...");

        lblErrorCapitalBase.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorCapitalBase.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorCapitalBase.setText("Debe ser numérico");

        lblErrorCapitalBase1.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        lblErrorCapitalBase1.setForeground(new java.awt.Color(153, 204, 255));
        lblErrorCapitalBase1.setText("Debe ser numérico_____");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbApalancamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCapitalBase, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorCapitalBase, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFondoDeNegocio, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                            .addComponent(txtFinanciamiento)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblCalificacionBancaria)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesempleo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCrecimientoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(lblErrorCapitalBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCrecimientoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesempleo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorCapitalBase1))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCapitalBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorCapitalBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbApalancamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFinanciamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtFondoDeNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblCalificacionBancaria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 102));
        jMenuBar1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jMenu1.setText("Archivo");

        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuardar);

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbrir);
        jMenu1.add(jSeparator1);

        menuReporte.setText("Reporte");
        menuReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteActionPerformed(evt);
            }
        });
        jMenu1.add(menuReporte);
        jMenu1.add(jSeparator2);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        menuFondeo.setText("Fondeo");
        menuFondeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondeoActionPerformed(evt);
            }
        });
        jMenu2.add(menuFondeo);

        menuLineasNegocio.setText("Líneas de Negocio");
        menuLineasNegocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLineasNegocioActionPerformed(evt);
            }
        });
        jMenu2.add(menuLineasNegocio);

        menuCarteras.setText("Carteras");
        menuCarteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarterasActionPerformed(evt);
            }
        });
        jMenu2.add(menuCarteras);

        menuTablaMora.setText("Tabla Mora");
        menuTablaMora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablaMoraActionPerformed(evt);
            }
        });
        jMenu2.add(menuTablaMora);

        menuLiquidez.setText("Liquidez");
        menuLiquidez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLiquidezActionPerformed(evt);
            }
        });
        jMenu2.add(menuLiquidez);

        menuSuficiencia.setText("Suficiencia");
        menuSuficiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuficienciaActionPerformed(evt);
            }
        });
        jMenu2.add(menuSuficiencia);

        menuCoberturas.setText("Coberturas");
        menuCoberturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCoberturasActionPerformed(evt);
            }
        });
        jMenu2.add(menuCoberturas);

        menuSolvencias.setText("Solvencia");
        menuSolvencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSolvenciasActionPerformed(evt);
            }
        });
        jMenu2.add(menuSolvencias);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarMisComponentes(){
        this.txtCrecimientoEconomico.setText("8%");
        this.txtDesempleo.setText("15%");
        
        this.lblErrorCapitalBase.setVisible(false);
        this.lblErrorPorcentajeConsumo.setVisible(false);
        this.lblErrorPorcentajeHipotecario.setVisible(false);
        this.lblErrorPorcentajeCorporativo.setVisible(false);
        this.lblErrorPorcentajeInversiones.setVisible(false);
        
        this.txtCapitalBase.requestFocus();
    }
    
    
    private void menuFondeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondeoActionPerformed
        VentanaFondeo ventanaFondeo = new VentanaFondeo(this, true);
        ventanaFondeo.estructura = this.estructura;
        ventanaFondeo.setVisible(true);
    }//GEN-LAST:event_menuFondeoActionPerformed

    private void menuLineasNegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLineasNegocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLineasNegocioActionPerformed

    private void menuCarterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarterasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCarterasActionPerformed

    private void menuTablaMoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaMoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuTablaMoraActionPerformed

    private void menuLiquidezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLiquidezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLiquidezActionPerformed

    private void menuSuficienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuficienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSuficienciaActionPerformed

    private void menuCoberturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCoberturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCoberturasActionPerformed

    private void menuSolvenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSolvenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSolvenciasActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuReporteActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void txtCapitalBaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapitalBaseKeyReleased
        
        calcularEstructura();
    }//GEN-LAST:event_txtCapitalBaseKeyReleased

    private void cmbApalancamientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbApalancamientoItemStateChanged
        calcularEstructura();
    }//GEN-LAST:event_cmbApalancamientoItemStateChanged

    private void cmbPorcentajeOperacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPorcentajeOperacionesItemStateChanged

        this.calcularEnfoqueNegocio();
    }//GEN-LAST:event_cmbPorcentajeOperacionesItemStateChanged

    private void txtPorcentajeInversionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeInversionesKeyReleased

        this.calcularEnfoqueNegocio();
    }//GEN-LAST:event_txtPorcentajeInversionesKeyReleased

    private void txtPorcentajeCorporativoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeCorporativoKeyReleased

        this.calcularCarteras();
    }//GEN-LAST:event_txtPorcentajeCorporativoKeyReleased

    private void txtPorcentajeHipotecarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeHipotecarioKeyReleased

        this.calcularCarteras();
    }//GEN-LAST:event_txtPorcentajeHipotecarioKeyReleased

    private void txtPorcentajeConsumoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeConsumoKeyReleased

        this.calcularCarteras();
    }//GEN-LAST:event_txtPorcentajeConsumoKeyReleased

    private void calcularEstructura(){
        
        try{
            String textoCapitalBase = txtCapitalBase.getText();
            this.lblErrorCapitalBase.setVisible(false);
            
            if(textoCapitalBase.trim().equals("")){
                return;
            }
            
            this.estructura.capital = new BigDecimal(textoCapitalBase);//Double.parseDouble(textoCapitalBase);
        }
        catch(Exception ex){
            this.lblErrorCapitalBase.setText("Debe ser numérico");
            this.lblErrorCapitalBase.setVisible(true);
        }
        
        
        
        try{
            String textoApalancamiento = cmbApalancamiento.getSelectedItem().toString();
            
            this.estructura.apalancamiento = Integer.parseInt(textoApalancamiento);
        }
        catch(Exception ex){
        }
        
        
        
        try{
            this.estructura.financiamiento = this.estructura.calcularFinanciamiento(this.estructura.capital, this.estructura.apalancamiento);
            this.estructura.calcularFondoDeNegocio(this.estructura.capital, this.estructura.apalancamiento); // establece el fondo de negocio
            
            txtFinanciamiento.setText("" + this.estructura.financiamiento);
            txtFondoDeNegocio.setText("" + this.estructura.fondoDeNegocio);
            
            lblCalificacionBancaria.setText(this.estructura.calificacionBancaria);
        }
        catch(Exception ex){
        }
    }
    
    private void calcularCarteras(){
        
        try{
            String textoConsumo = txtPorcentajeConsumo.getText();
            
            this.lblErrorPorcentajeConsumo.setVisible(false);
            
            this.estructura.porcentajeConsumo = Integer.parseInt(textoConsumo);
        }
        catch(Exception ex){
            this.lblErrorPorcentajeConsumo.setText("Debe ser numérico");
            this.lblErrorPorcentajeConsumo.setVisible(true);
        }
        
        
        
        try{
            String textoHipotecario = txtPorcentajeHipotecario.getText();
            
            this.lblErrorPorcentajeHipotecario.setVisible(false);
            
            this.estructura.porcentajeHipotecario = Integer.parseInt(textoHipotecario);
        }
        catch(Exception ex){
            this.lblErrorPorcentajeHipotecario.setText("Debe ser numérico");
            this.lblErrorPorcentajeHipotecario.setVisible(true);
        }
        
        
        
        
        try{
            String textoCorporativo = txtPorcentajeCorporativo.getText();
            
            this.lblErrorPorcentajeCorporativo.setVisible(false);
            
            this.estructura.porcentajeCorporativo = Integer.parseInt(textoCorporativo);
        }
        catch(Exception ex){
            this.lblErrorPorcentajeCorporativo.setText("Debe ser numérico");
            this.lblErrorPorcentajeCorporativo.setVisible(true);
        }
        
        
        this.estructura.carteras = this.estructura.calcularCarteras(this.estructura.porcentajeConsumo,
                                                                    this.estructura.porcentajeHipotecario,
                                                                    this.estructura.porcentajeCorporativo);
    }
    
    private void calcularEnfoqueNegocio(){
        
        try{
            String textoInversiones = txtPorcentajeInversiones.getText();
            this.lblErrorPorcentajeInversiones.setVisible(false);
            
            this.estructura.porcentajeInversiones = Integer.parseInt(textoInversiones);
        }
        catch(Exception ex){
            this.lblErrorPorcentajeInversiones.setText("Debe ser numérico");
            this.lblErrorPorcentajeInversiones.setVisible(true);
        }
        
        
        
        try{
            String textoOperaciones = cmbPorcentajeOperaciones.getSelectedItem().toString();
            
            this.estructura.porcentajeOperaciones = Integer.parseInt(textoOperaciones);
        }
        catch(Exception ex){
        }
        
        
        
        try{
            this.estructura.calcularPorcentajeOperacionaes(this.estructura.porcentajeOperaciones);
            this.estructura.establecerApetitoRiesgo(this.estructura.porcentajeConsumo);
            this.estructura.enfoqueDeNegocio = this.estructura.calcularEnfoqueNegocio();
            
            lblApetitoRiesgo.setText(this.estructura.apetitoRiesgo);
            txtEnfoqueDeNegocio.setText(this.estructura.enfoqueDeNegocio);
        }
        catch(Exception ex){
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbApalancamiento;
    private javax.swing.JComboBox<String> cmbPorcentajeOperaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblApetitoRiesgo;
    private javax.swing.JLabel lblCalificacionBancaria;
    private javax.swing.JLabel lblErrorCapitalBase;
    private javax.swing.JLabel lblErrorCapitalBase1;
    private javax.swing.JLabel lblErrorPorcentajeConsumo;
    private javax.swing.JLabel lblErrorPorcentajeConsumo1;
    private javax.swing.JLabel lblErrorPorcentajeCorporativo;
    private javax.swing.JLabel lblErrorPorcentajeHipotecario;
    private javax.swing.JLabel lblErrorPorcentajeInversiones;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuCarteras;
    private javax.swing.JMenuItem menuCoberturas;
    private javax.swing.JMenuItem menuFondeo;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuLineasNegocio;
    private javax.swing.JMenuItem menuLiquidez;
    private javax.swing.JMenuItem menuReporte;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuSolvencias;
    private javax.swing.JMenuItem menuSuficiencia;
    private javax.swing.JMenuItem menuTablaMora;
    private javax.swing.JTextField txtCapitalBase;
    private javax.swing.JTextField txtCrecimientoEconomico;
    private javax.swing.JTextField txtDesempleo;
    private javax.swing.JTextField txtEnfoqueDeNegocio;
    private javax.swing.JTextField txtFinanciamiento;
    private javax.swing.JTextField txtFondoDeNegocio;
    private javax.swing.JTextField txtPorcentajeConsumo;
    private javax.swing.JTextField txtPorcentajeCorporativo;
    private javax.swing.JTextField txtPorcentajeHipotecario;
    private javax.swing.JTextField txtPorcentajeInversiones;
    // End of variables declaration//GEN-END:variables
}
